apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-infra-nginx
  labels:
    app: app-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-nginx
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      containers:
      - name: app-nginx
        image: 23344999900.dkr.ecr.ap-south-1.amazonaws.com/platform-infra-nginx:githash
        imagePullPolicy: IfNotPresent
        imagePullSecrets:
        - name: "regcred"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "200m"
      tolerations:
      - key: "spot"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: arch
                operator: In
                values:
                - arm
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - app-nginx
              topologyKey: kubernetes.io/hostname
        topologySpreadConstraints: # this is for multi az for high availability
        - maxSkew: 1
          topologyKey: kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - app-nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: app-demo-service-nginx
  labels:
    app: app-nginx
spec:
  type: ClusterIP
  selector:
    app: app-nginx
  ports:
  - port: 80
    targetPort: 80
